### ISSUE TITLE
Productivity Analytics

### ISSUE THREAD

**Issue by SebZG** [SebZG/pomo-quad#13]
### User Story

As a user, I want to see analytics on my tasks and Pomodoro sessions, so I can understand and improve my productivity.

### Acceptance Criteria

- [ ] Display a summary of tasks completed per quadrant.
- [ ] Show the number of Pomodoro sessions completed in a day or week.

### Tasks

- [ ] Build a dashboard to display analytics.
- [ ] Use charts or graphs for visualization.
