### ISSUE TITLE
Onboarding Tutorial

### ISSUE THREAD

**Issue by SebZG** [SebZG/pomo-quad#15]
### User Story

As a new user, I want a guided tutorial, so I can quickly understand how to use the app.

### Acceptance Criteria

- [ ] Tutorial guides users through key features.
- [ ] Users can skip or revisit the tutorial.

### Tasks

- [ ] Create an onboarding flow using modals or a guided UI overlay.
- [ ] Add a "Help" section to revisit the tutorial.
