### ISSUE TITLE
Notifications for Timer

### ISSUE THREAD

**Issue by SebZG** [SebZG/pomo-quad#5]
### User Story

As a user, I want notifications at the end of focus and break sessions, so I can stay on track.

### Acceptance Criteria

- [ ] Notifications trigger at the end of sessions.
- [ ] Notifications can be enabled/disabled in settings.

### Tasks

- [ ] Use browser Notification API to send alerts.
- [ ] Add a toggle to enable/disable notifications.
